apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.3.1
    helm:
  values: |
    grafana:
      adminPassword: admin123
      service:
        type: NodePort
      resources:
        requests:
          memory: 200Mi
        limits:
          memory: 400Mi
      nodeSelector:
        workload: heavy

    prometheus:
      prometheusSpec:
        retention: 3d
        scrapeInterval: 30s
        nodeSelector:
          workload: heavy
        resources:
          requests:
            memory: 400Mi
          limits:
            memory: 700Mi

    alertmanager:
      enabled: false

    # Disable heavy components (BIG WIN for Pi)
    kubeEtcd:
      enabled: false

    kubeScheduler:
      enabled: false

    kubeControllerManager:
      enabled: false

    kubeProxy:
      enabled: false

    # Optional: reduce exporters overhead
    nodeExporter:
      resources:
        requests:
          memory: 50Mi
        limits:
          memory: 100Mi