apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.41.0
    helm:
      values: |
        loki:
          auth_enabled: false

        singleBinary:
          replicas: 1
        nodeSelector:
          node-type: high-perf

        requests:
          cpu: 50m
          memory: 256Mi
        storage:
          type: filesystem
        monitoring:
          selfMonitoring:
            enabled: false
        grafanaAgent:
          enabled: false
        grafanaAgentOperator:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true